[package]
workspace = ".."
name = "iced_theme_manager"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git" , features = ["glow", "glow_default_system_font"], default-features = false }
iced_theme = { path = "../theme" }
