[package]
workspace = ".."
name = "iced_theme"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
iced = { version = "0.3", features = ["glow", "glow_default_system_font"], default-features = false }
