[package]
workspace = ".."
name = "iced_theme"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git" , features = ["glow", "glow_default_system_font"], default-features = false }
